[package]
name = "entries"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
ark-bn254 = "0.4"
ark-serialize = "0.4"
hex = "0.4"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"

jolt-core = { workspace = true }
